//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argin.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalculatorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalculatorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Argin.Extensions.Resources.CalculatorStrings", typeof(CalculatorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allotment:.
        /// </summary>
        public static string AllotmentText {
            get {
                return ResourceManager.GetString("AllotmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To break even, you should have a final share price of.
        /// </summary>
        public static string BreakEvenText {
            get {
                return ResourceManager.GetString("BreakEvenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string CostText {
            get {
                return ResourceManager.GetString("CostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Profit %:.
        /// </summary>
        public static string DesiredProfitPercentText {
            get {
                return ResourceManager.GetString("DesiredProfitPercentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Share Price:.
        /// </summary>
        public static string FinalSharePriceText {
            get {
                return ResourceManager.GetString("FinalSharePriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a {0}% return, you should have a final share price of.
        /// </summary>
        public static string FinalShareReturnText {
            get {
                return ResourceManager.GetString("FinalShareReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Share Price:.
        /// </summary>
        public static string InitialSharePriceText {
            get {
                return ResourceManager.GetString("InitialSharePriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker Fee:.
        /// </summary>
        public static string MakerFeePercentText {
            get {
                return ResourceManager.GetString("MakerFeePercentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Profit.
        /// </summary>
        public static string NetProfitText {
            get {
                return ResourceManager.GetString("NetProfitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceeds.
        /// </summary>
        public static string ProceedsText {
            get {
                return ResourceManager.GetString("ProceedsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return on Investment.
        /// </summary>
        public static string RoIText {
            get {
                return ResourceManager.GetString("RoIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taker Fee:.
        /// </summary>
        public static string TakerFeePercentText {
            get {
                return ResourceManager.GetString("TakerFeePercentText", resourceCulture);
            }
        }
    }
}
